services:
  - type: web
    name: arukemisuto-autoclick
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
